// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AeonDave/mp-quic-go (interfaces: AckFrameSource)
//
// Generated by this command:
//
//	mockgen -typed -build_flags=-tags=gomock -package quic -self_package github.com/AeonDave/mp-quic-go -destination mock_ack_frame_source_test.go github.com/AeonDave/mp-quic-go AckFrameSource
//

// Package quic is a generated GoMock package.
package quic

import (
	reflect "reflect"

	monotime "github.com/AeonDave/mp-quic-go/internal/monotime"
	protocol "github.com/AeonDave/mp-quic-go/internal/protocol"
	wire "github.com/AeonDave/mp-quic-go/internal/wire"
	gomock "go.uber.org/mock/gomock"
)

// MockAckFrameSource is a mock of AckFrameSource interface.
type MockAckFrameSource struct {
	ctrl     *gomock.Controller
	recorder *MockAckFrameSourceMockRecorder
	isgomock struct{}
}

// MockAckFrameSourceMockRecorder is the mock recorder for MockAckFrameSource.
type MockAckFrameSourceMockRecorder struct {
	mock *MockAckFrameSource
}

// NewMockAckFrameSource creates a new mock instance.
func NewMockAckFrameSource(ctrl *gomock.Controller) *MockAckFrameSource {
	mock := &MockAckFrameSource{ctrl: ctrl}
	mock.recorder = &MockAckFrameSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAckFrameSource) EXPECT() *MockAckFrameSourceMockRecorder {
	return m.recorder
}

// AckDuePaths mocks base method.
func (m *MockAckFrameSource) AckDuePaths(now monotime.Time) []protocol.PathID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckDuePaths", now)
	ret0, _ := ret[0].([]protocol.PathID)
	return ret0
}

// AckDuePaths indicates an expected call of AckDuePaths.
func (mr *MockAckFrameSourceMockRecorder) AckDuePaths(now any) *MockAckFrameSourceAckDuePathsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckDuePaths", reflect.TypeOf((*MockAckFrameSource)(nil).AckDuePaths), now)
	return &MockAckFrameSourceAckDuePathsCall{Call: call}
}

// MockAckFrameSourceAckDuePathsCall wrap *gomock.Call
type MockAckFrameSourceAckDuePathsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAckFrameSourceAckDuePathsCall) Return(arg0 []protocol.PathID) *MockAckFrameSourceAckDuePathsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAckFrameSourceAckDuePathsCall) Do(f func(monotime.Time) []protocol.PathID) *MockAckFrameSourceAckDuePathsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAckFrameSourceAckDuePathsCall) DoAndReturn(f func(monotime.Time) []protocol.PathID) *MockAckFrameSourceAckDuePathsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAckFrame mocks base method.
func (m *MockAckFrameSource) GetAckFrame(arg0 protocol.EncryptionLevel, now monotime.Time, onlyIfQueued bool, pathID protocol.PathID) *wire.AckFrame {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAckFrame", arg0, now, onlyIfQueued, pathID)
	ret0, _ := ret[0].(*wire.AckFrame)
	return ret0
}

// GetAckFrame indicates an expected call of GetAckFrame.
func (mr *MockAckFrameSourceMockRecorder) GetAckFrame(arg0, now, onlyIfQueued, pathID any) *MockAckFrameSourceGetAckFrameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAckFrame", reflect.TypeOf((*MockAckFrameSource)(nil).GetAckFrame), arg0, now, onlyIfQueued, pathID)
	return &MockAckFrameSourceGetAckFrameCall{Call: call}
}

// MockAckFrameSourceGetAckFrameCall wrap *gomock.Call
type MockAckFrameSourceGetAckFrameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAckFrameSourceGetAckFrameCall) Return(arg0 *wire.AckFrame) *MockAckFrameSourceGetAckFrameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAckFrameSourceGetAckFrameCall) Do(f func(protocol.EncryptionLevel, monotime.Time, bool, protocol.PathID) *wire.AckFrame) *MockAckFrameSourceGetAckFrameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAckFrameSourceGetAckFrameCall) DoAndReturn(f func(protocol.EncryptionLevel, monotime.Time, bool, protocol.PathID) *wire.AckFrame) *MockAckFrameSourceGetAckFrameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
